food/urls.py
from . import views
from django.urls import path


app_name = 'food'
urlpatterns = [
    path('', views.index, name='index'),
    path('<int:item_id>/', views.detail, name='detail'),
    path('item/', views.item, name='item'),
    path('add', views.create_item, name='create_item'),
    path('update/<int:id>/', views.update_item, name='update_item'),
    path('delete/<int:id>', views.delete_item, name='delete_item'),
]

mysite/urls.py
from django.contrib import admin
from django.urls import include,path
from users import views as users_views
urlpatterns = [
    path('admin/', admin.site.urls),
    path('food/', include('food.urls')),
    path('register/',users_views.register, name='register')
]

food/models.py
from django.db import models

# Create your models here.
class Item(models.Model):

    def __str__(self):
        return self.item_name
        
    item_name = models.CharField(max_length=200)
    item_desc = models.CharField(max_length=200)
    item_price = models.IntegerField()
    item_image = models.CharField(max_length=500, default="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQp8MdrNj1NpuBB2kQuEmLxgqn9y3ZZWiAipWbkfzkLIN2DGTQ6U9A7LFQH_i5a1fYjtJg&usqp=CAU")

users/models.py
from django.db import models

# Create your models here.

food/forms.py
from django import forms
from .models import Item

class ItemForm(forms.ModelForm):
    class Meta:
        model = Item
        fields = ['item_name', 'item_desc', 'item_price', 'item_image']

food/views.py
from django.shortcuts import redirect, render
from django.http import HttpResponse

from .forms import ItemForm
from .models import Item
from django.template import loader


# Create your views here.
def index(request):
    item_list = Item.objects.all()
    context = {
        'item_list': item_list,
    }
    return render(request, 'food/index.html', context)

def item(request):
    return HttpResponse('<h1>This is an item view</h1>')

def detail(request, item_id):
    item = Item.objects.get(pk=item_id)
    context = {
        'item' : item
    }
    return render(request, 'food/detail.html', context)

def create_item(request):
    form = ItemForm(request.POST or None)
    if form.is_valid():
        form.save()
        return redirect('food:index')
    return render(request,'food/item-form.html',{'form': form} )

def update_item(request, id):
    item = Item.objects.get(id=id)
    form = ItemForm(request.POST or None, instance=item)
    if form.is_valid():
        form.save()
        return redirect('food:index')
    return render(request, 'food/item-form.html', {'form':form, 'item':item})

def delete_item(request, id):
    item = Item.objects.get(id=id)
    if request.method == 'POST':
        item.delete()
        return redirect('food:index')
    return render(request,'food/item-delete.html',{'item': item})

users/views.py
from django.shortcuts import render
from django.contrib.auth.forms import UserCreationForm

# Create your views here.
def register(request):
    form = UserCreationForm()
    return render (request, 'users/register.html', {'form': form})

food/templates/food/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <link rel="stylesheet" type="text/css" href="{% static 'food/styles.css' %}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>

    <title>Document</title>
</head>
<body>
<!--
 <nav class="navbar navbar-expand-lg bg-body-tertiary">
-->
    <nav class="navbar navbar-dark bg-black">

        <a href="#" class="navbar-brand">FoodApp</a>
        <div class="navbar d-flex gap-2">
            <a class="nav-item nav-link text-primary" href="{% url 'food:create_item' %}">Add Item</a>
            <a class="nav-item nav-link text-primary" href="#">Delete Item</a>
            <a class="nav-item nav-link text-primary" href="#">View Item</a>
        </div>
    </nav>
    {% block body %}
    {% endblock %}
    
</body>
</html>

food/templates/food/detail.html
{% extends 'food/base.html' %}


{% block body %}
<div class="container">
    <div class="row">
        <div class="col-md-6">
            <img height="300px" src="{{item.item_image}}" alt="" class="card">
        </div>
        <div class="col-md-6">

            <h1>{{ item.item_name}}</h1>
            <h2>{{ item.item_desc}}</h2>
            <h2>${{ item.item_price}}</h2>
            <a href="{% url 'food:delete_item' item.id %}">Delete</a>
        </div>
    </div>
</div>

{% endblock %}

food/templates/food/index.html
{% extends 'food/base.html' %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Food App</title>
</head>
<body>
   
    {% block body %}
    {% for item in item_list %}
        <div class="row mb-4">
            <div class="col-md-3 offset-md-2">
                <img class="card" height="150px" style="max-width: 100%" src="{{item.item_image}}"/>

            </div>
            <div class="col-md-4">
                <h3>{{ item.item_name}}</h3>
                <h5>{{ item.item_desc}}</h5>
                <h6>{{ item.item_price}}</h6>

            </div>
            <div class="col-md-2">
                <a href="{% url 'food:detail' item.id %}" class="btn btn-success">Details</a>
            </div>
        </div>


    {% endfor %}
    {% endblock%}

</body>
</html>

food/templates/food/item-delete.html
<form method="POST">
    {% csrf_token%}
    <h2>Are you sure you want to delete {{ item.item_name }}</h2>
    <button type="submit">Confirm</button>
</form>

food/templates/food/item-form.html
{% extends 'food/base.html' %}
{% block body %}
<form method="POST">
    {% csrf_token %}
    {{ form }}
    <button type="submit">Save</button>
</form>
{% endblock %}

users/templates/users/register.html
<form method="POST">
    {% csrf_token %}
    {{ form }}
    <button type="submit">Signup</button>
</form>